EXTERNAL wait(seconds)
EXTERNAL print_error(text)
EXTERNAL print(object_id, text)
EXTERNAL move_object_by(object_id, x, y)
EXTERNAL move_object_to(object_id, x, y)
EXTERNAL destroy_object(object_id)
EXTERNAL get_game_var(var_name)